stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion.py
    deps:
      - src/pipeline/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/pipeline/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/pipeline/data_preprocessing.py
    outs:
      - data/processed
