stages:
  data_ingestion:
    cmd: python src/pipeline/data_ingestion.py
    deps:
      - src/pipeline/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/pipeline/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/pipeline/data_preprocessing.py
    outs:
      - data/processed

  model_building:
    cmd: python src/pipeline/model_building.py
    deps:
      - data/processed/train_processed.csv
      - src/pipeline/model_building.py
    params:
      - model_building.max_features
      - model_building.ngram_range
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl

  model_evaluation:
    cmd: python src/pipeline/model_evaluation.py
    deps:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
      - lgbm_model.pkl
      - tfidf_vectorizer.pkl
      - src/pipeline/model_evaluation.py
    outs:
      - model_evaluation.json

  model_registration:
    cmd: python src/pipeline/register_model.py
    deps:
      - model_evaluation.json
      - src/pipeline/register_model.py



